[workspace]
members = [
    "server",
    "client",
    "common",
]
resolver = "2"

[workspace.package]
version = "0.1.1"
edition = "2021"
authors = ["gagansuie <https://github.com/gagansuie>"]
license = "MIT OR Apache-2.0"

[workspace.dependencies]
tokio = { version = "1.35", features = ["full"] }
quinn = "0.10"
rustls = "0.21"
rustls-pemfile = "1.0"
rcgen = "0.12"
reed-solomon-erasure = "6.0"
boringtun = "0.6"
base64 = "0.21"
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
bytes = "1.5"
lz4_flex = "0.11"
etherparse = "0.14"
socket2 = { version = "0.5", features = ["all"] }
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
prometheus = "0.13"
hyper = { version = "0.14", features = ["server", "tcp", "http1"] }
